version: '3.8'

volumes:
  postgres-data:
  client-dist:

services:
  db:
    env_file:
      - ./.env
      - ./.env.production.local
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    ports:
      # внешний порт : внутренний порт
      - 5432:5432
    container_name: todos-db

  server:
    build: ./server
    env_file:
      - ./.env
      - ./.env.production.local
    working_dir: /root/server
    depends_on:
      - db
    volumes:
      - client-dist:/root/client/dist:delegated
    ports:
      - 3000:${PORT}
    container_name: todos-server

  client:
    build: ./client
    working_dir: /root/client
    container_name: todos-client
    volumes:
      - client-dist:/root/client/dist:delegated

  # по умолчанию запускается раз в день
  backup:
    env_file:
      - docker.env
    image: prodrigestivill/postgres-backup-local
    volumes:
      - ~/pgbackups/todos:/backups # путь на хост-компьютере для хранения резервных копий
    environment:
      - SCHEDULE=* * * * * # каждую минуту
    depends_on:
      - db
    container_name: todos-db-backup

  # logs ui
  dozzle:
    container_name: todos-dozzle
    image: amir20/dozzle:v5.0.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
